### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by GAMEA9G** [FujiwaraChoki/TeleSync#3]
Could not find platform independent libraries <prefix>
Traceback (most recent call last):
  File "C:\Users\best\PycharmProjects\cloudtelgrambot\TeleSync\src\main.py", line 111, in <module>
    main()
  File "C:\Users\best\PycharmProjects\cloudtelgrambot\TeleSync\src\main.py", line 52, in main
    command = args[1]
              ~~~~^^^
IndexError: list index out of range

Process finished with exit code -1073741819 (0xC0000005)

**Comment by FujiwaraChoki** [comment]
well yeah.. you have to provide arguments..
